# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Jierui Zuo # the website title (if blank, full name will be used instead)
first_name: Jierui
middle_name: (Jerry)
last_name: Zuo
contact_note: >
  Email is the best way to reach me.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Research at the intersection of AI, learning, and decision-making.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: AI, decision-making, bandits, stochastic systems, experiment design, human-AI collaboration, intelligent systems, operations research
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ♟️ # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://zuojr.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# External service URLs for repository page
# To use a different instance or service for displaying GitHub stats and trophies,
# update these URLs. These are used in the repository templates.
external_services:
  github_readme_stats_url: https://github-readme-stats.vercel.app
  github_profile_trophy_url: https://github-profile-trophy.vercel.app

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# see https://schema.org/docs/faq.html for more information
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
cronitor_analytics: # cronitor RUM analytics site ID (format: XXXXXXXXX)
pirsch_analytics: # your Pirsch analytics site ID (length 32 characters)
openpanel_analytics: # your Openpanel analytics client ID (format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)

google_site_verification: # your google-site-verification ID (Google Search Console)
bing_site_verification: # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Blog # blog_name will be displayed in your blog page
blog_description: Notes on research, AI, and decision-making.
permalink: /blog/:year/:title/
lsi: false # produce an index for related posts

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo: # <your-github-user-name>/<your-github-repo-name>
  repo_id: # leave empty or specify your repo_id (see https://giscus.app/)
  category: Comments # name of the category under which discussions will be created
  category_id: # leave empty or specify your category_id (see https://giscus.app/)
  mapping: title # identify discussions by post title
  strict: 1 # use strict identification mode
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: bottom # whether to display input form below (bottom) or above (top) the comments
  dark_theme: dark # name of the dark color scheme (preferred works well with al-folio dark mode)
  light_theme: light # name of the light color scheme (preferred works well with al-folio light mode)
  emit_metadata: 0
  lang: en

disqus_shortname:

# External sources.
external_sources:

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint: # your loops endpoint (e.g., https://app.loops.so/api/newsletter-form/YOUR-ENDPOINT)

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true
  teachings:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-3rd-party-libraries
  - jekyll-archives-v2
  - jekyll-cache-bust
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-socials
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      citations: true
      related_posts: true
      bibtex: false
  - scope:
      path: ""
      type: "news"
    values:
      layout: post
      permalink: /news/:title/
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "teachings"
    values:
      layout: post
      permalink: /teaching/:title/

# Jekyll Archives
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
    category: "/blog/category/:name/"

display_tags: [AI, decision-making, bandits, stochastic-systems]
display_categories: [research, notes]

# Pagination path
paginate_path: /blog/page/:num/

# Build settings
sass:
  style: compressed
  sourcemap: never
  quiet_deps: true

autoprefixer:
  browsers:
    - last 2 versions

# ---------------------------------------------------------------------------- #
# Optional Features
# ---------------------------------------------------------------------------- #

enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_progressbar: true
enable_project_categories: true
enable_medium_zoom: true
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true

# ---------------------------------------------------------------------------- #
# Bibliography
# ---------------------------------------------------------------------------- #
scholar:
  last_name: [Zuo]
  first_name: [Jierui]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# ---------------------------------------------------------------------------- #
# HTML Compression
# ---------------------------------------------------------------------------- #
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
